"""MyTool: runtime state inspection and configuration for the agent loop."""

from __future__ import annotations

import json
import re
import time
from typing import TYPE_CHECKING, Any

from loguru import logger

from nanobot.agent.tools.base import Tool
from nanobot.agent.tools.context import ContextAware, RequestContext, current_request_context
from nanobot.agent.tools.runtime_state import RuntimeState
from nanobot.config_base import Base

if TYPE_CHECKING:
    from nanobot.agent.subagent import SubagentStatus


GLOBAL_SESSION_KEY = "__global__"

# Expanded secret-shaped value regex (D14). Catches common credential shapes so
# they never reach audit logs or chat-visible tool output.
_SECRET_VALUE_RE = re.compile(
    r"^(sk-[A-Za-z0-9]{20,}|"
    r"Bearer\s+[A-Za-z0-9_\-\.]{10,}|"
    r"xox[bpoar]-[A-Za-z0-9\-]+|"
    r"gh[ps]_[A-Za-z0-9]{20,}|"
    r"AIza[0-9A-Za-z_-]{30,}|"
    r"AKIA[0-9A-Z]{16}|"
    r"ASIA[0-9A-Z]{16}|"
    r"Basic\s+[A-Za-z0-9+/=]{10,}|"
    r"eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*|"
    r"-----BEGIN\s+(RSA\s+|OPENSSH\s+|EC\s+|DSA\s+)?PRIVATE KEY-----|"
    r"[A-Fa-f0-9]{64}|"
    r"[A-Za-z0-9_-]{40,}$)"
)


class MyToolConfig(Base):
    """Self-inspection tool configuration."""
    enable: bool = True
    allow_set: bool = False
    allow_scratchpad: bool = False
    require_context: bool = False
    session_isolation: bool = True


def _has_real_attr(obj: Any, key: str) -> bool:
    """Check if obj has a real (explicitly set) attribute, not auto-generated by mock."""
    if isinstance(obj, dict):
        return key in obj
    d = getattr(obj, "__dict__", None)
    if d is not None and key in d:
        return True
    for cls in type(obj).__mro__:
        if key in cls.__dict__:
            return True
    return False


def _is_subagent_status(value: Any) -> bool:
    from nanobot.agent.subagent import SubagentStatus

    return isinstance(value, SubagentStatus)


class MyTool(Tool, ContextAware):
    """Check and set the agent loop's runtime configuration."""

    _plugin_discoverable = False  # Requires AgentLoop reference; registered manually
    # D17: core-only — subagents never receive `my` (no scratchpad access from
    # child agents). Excluded from scope="subagent" on two counts: this flag and
    # _plugin_discoverable=False above.
    _scopes = {"core"}
    config_key = "my"

    @classmethod
    def config_cls(cls):
        return MyToolConfig

    @classmethod
    def enabled(cls, ctx: Any) -> bool:
        return ctx.config.my.enable

    BLOCKED = frozenset({
        # Core infrastructure
        "bus", "provider", "_running", "tools",
        # Config management
        "_runtime_vars",
        # Subsystems
        "runner", "sessions", "consolidator",
        "dream", "auto_compact", "context", "commands",
        # Sensitive runtime state (credentials, message routing, task tracking)
        "_mcp_servers", "_mcp_stacks", "_pending_queues",
        "_session_locks", "_active_tasks", "_background_tasks",
        # Security boundaries (inspect + modify both blocked)
        "restrict_to_workspace", "channels_config",
        "_concurrency_gate", "_unified_session", "_extra_hooks",
    })

    READ_ONLY = frozenset({
        "subagents",  # observable but replacing it would break the system
        "_current_iteration",  # updated by runner only
        "exec_config",  # inspect allowed (e.g. check sandbox), modify blocked
        "web_config",  # inspect allowed (e.g. check enable), modify blocked
        "workspace_sandbox",  # read-only view of workspace enforcement level
    })

    _DENIED_ATTRS = frozenset({
        "__class__", "__dict__", "__bases__", "__subclasses__", "__mro__",
        "__init__", "__new__", "__reduce__", "__getstate__", "__setstate__",
        "__del__", "__call__", "__getattr__", "__setattr__", "__delattr__",
        "__code__", "__globals__", "func_globals", "func_code",
        "__wrapped__", "__closure__",
    })

    # Sub-field names that are sensitive regardless of parent path
    _SENSITIVE_NAMES = frozenset({
        "api_key", "secret", "password", "token", "credential",
        "private_key", "access_token", "refresh_token", "auth",
    })

    @classmethod
    def _is_sensitive_field_name(cls, name: str) -> bool:
        lowered = name.lower()
        return lowered in cls._SENSITIVE_NAMES or any(
            part in cls._SENSITIVE_NAMES for part in lowered.split("_")
        )

    RESTRICTED: dict[str, dict[str, Any]] = {
        "max_iterations":        {"type": int, "min": 1,   "max": 100},
        "context_window_tokens": {"type": int, "min": 4096, "max": 1_000_000},
        "model":                 {"type": str, "min_len": 1},
    }

    _MAX_RUNTIME_KEYS = 64
    _MAX_VALUE_BYTES = 8192

    def __init__(
        self,
        runtime_state: RuntimeState,
        modify_allowed: bool = True,
        allow_scratchpad: bool = False,
        require_context: bool = False,
        session_isolation: bool = True,
    ) -> None:
        self._runtime_state = runtime_state
        self._modify_allowed = modify_allowed
        self._allow_scratchpad = allow_scratchpad
        self._require_context = require_context
        self._session_isolation = session_isolation
        self._channel = ""
        self._chat_id = ""

    def __deepcopy__(self, memo: dict[int, Any]) -> MyTool:
        cls = self.__class__
        result = cls.__new__(cls)
        memo[id(self)] = result
        result._runtime_state = self._runtime_state
        result._modify_allowed = self._modify_allowed
        result._allow_scratchpad = self._allow_scratchpad
        result._require_context = self._require_context
        result._session_isolation = self._session_isolation
        result._channel = self._channel
        result._chat_id = self._chat_id
        return result

    def set_context(self, ctx: RequestContext) -> None:
        self._channel = ctx.channel
        self._chat_id = ctx.chat_id

    @property
    def name(self) -> str:
        return "my"

    @property
    def description(self) -> str:
        base = (
            "Check and set your own runtime state.\n"
            "Actions: check, set.\n"
            "- check (no key): full config overview — start here.\n"
            "- check (key): drill into a value. Dot-paths allowed "
            "(e.g. '_last_usage.prompt_tokens', 'web_config.enable').\n"
            "- set (key, value): change config or store notes in your scratchpad. "
            "Scratchpad keys persist across turns but not restarts.\n"
            "Key values: _current_iteration (current progress), "
            "max_iterations - _current_iteration = remaining iterations.\n"
            "Note: web_config and exec_config are readable but read-only.\n"
            "\n"
            "When to use:\n"
            "- User asks about your model, settings, or token usage → check that key.\n"
            "- User asks to switch to a named model preset → set model_preset to that preset name.\n"
            "- A tool fails or behaves unexpectedly → check the related config to diagnose.\n"
            "- User asks you to remember a preference for this session → set to store it in your scratchpad.\n"
            "- About to start a large task → check context_window_tokens and max_iterations first."
        )
        if not self._modify_allowed and not self._allow_scratchpad:
            base += "\nREAD-ONLY MODE: set is disabled."
        elif not self._modify_allowed and self._allow_scratchpad:
            base += (
                "\nSCRATCHPAD-ONLY MODE: set is limited to scratchpad keys "
                "(harmless per-session notes). Model, iterations, and other "
                "runtime state cannot be changed."
            )
        else:
            base += (
                "\nIMPORTANT: Before setting state, predict the potential impact. "
                "If the operation could cause crashes or instability "
                "(e.g. changing model), warn the user first."
            )
        return base

    @property
    def parameters(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["check", "set"],
                    "description": "Action to perform",
                },
                "key": {
                    "type": "string",
                    "description": "Dot-path for check/set. Examples: 'max_iterations', 'workspace', 'provider_retry_mode'. "
                    "Use 'model_preset' to switch named model presets. For check without key, shows all config values.",
                },
                "value": {"description": "New value (for set). Type must match target (int for max_iterations/context_window_tokens, str for model/model_preset)."},
            },
            "required": ["action"],
        }

    def _audit(self, action: str, detail: str) -> None:
        ctx = current_request_context()
        if ctx and ctx.session_key:
            session = ctx.session_key
        elif self._channel:
            session = f"{self._channel}:{self._chat_id}"
        else:
            session = "unknown"
        logger.info("self.{} | {} | session:{}", action, detail, session)

    # ------------------------------------------------------------------
    # Session scope helpers (D2, D3, D11, D12, D13)
    # ------------------------------------------------------------------

    _MAX_SESSIONS = 1024

    def _resolve_session_key(self) -> str | None:
        """Return the scratchpad session key, or None when ``require_context``
        is set and no request context is bound.

        Precedence (independent flags, D12/D13):
        - ``require_context`` is evaluated first: when set and no session is
          bound, it rejects the call (returns None) regardless of
          ``session_isolation``. This keeps the two flags independent as
          documented — an operator can enable the kill-switch without
          silently losing the context-rejection guarantee.
        - ``session_isolation=False`` forces everything to ``__global__``.
        - Otherwise the bound ``RequestContext.session_key`` is used, falling
          back to ``__global__`` when no context is bound.
        """
        ctx = current_request_context()
        key = ctx.session_key if ctx and ctx.session_key else None
        if key is None and self._require_context:
            return None
        if not self._session_isolation:
            return GLOBAL_SESSION_KEY
        if key is None:
            return GLOBAL_SESSION_KEY
        return key

    def _read_scope(self) -> dict[str, Any] | None:
        """Return the caller's per-session dict for reads (no creation).

        Returns an empty dict when the session has no scratchpad yet, and
        None only when ``require_context`` blocks the call.
        """
        key = self._resolve_session_key()
        if key is None:
            return None
        rc = self._runtime_state
        scoped = rc._runtime_vars.get(key)
        if scoped is None:
            return {}
        # Refresh LRU on access.
        rc._runtime_vars_lru[key] = time.monotonic()
        return scoped

    def _write_scope(self) -> dict[str, Any] | None:
        """Return the caller's per-session dict for writes, creating it lazily
        and enforcing the global session cap with LRU eviction.

        Must be called while holding ``_runtime_vars_lock``.
        Returns None when ``require_context`` blocks the call.
        """
        key = self._resolve_session_key()
        if key is None:
            return None
        rc = self._runtime_state
        scoped = rc._runtime_vars.get(key)
        if scoped is None:
            scoped = {}
            rc._runtime_vars[key] = scoped
            self._enforce_session_cap()
        rc._runtime_vars_lru[key] = time.monotonic()
        return scoped

    def _enforce_session_cap(self) -> None:
        """Evict least-recently-used sessions when over ``_MAX_SESSIONS``."""
        rc = self._runtime_state
        cap = self._MAX_SESSIONS
        while len(rc._runtime_vars) > cap:
            lru = rc._runtime_vars_lru
            if not lru:
                break
            # Never evict the global fallback scope.
            victim = min(
                (k for k in lru if k != GLOBAL_SESSION_KEY),
                key=lambda k: lru[k],
                default=None,
            )
            if victim is None:
                break
            rc._runtime_vars.pop(victim, None)
            lru.pop(victim, None)
            logger.info(
                "self.scratchpad | evicted session {} (cap {} reached) | "
                "scratchpad_session_count={}",
                victim, cap, len(rc._runtime_vars),
            )

    @staticmethod
    def _check_value_size(value: Any) -> str | None:
        """Reject values whose JSON encoding exceeds ``_MAX_VALUE_BYTES``."""
        try:
            encoded = json.dumps(value, default=str, ensure_ascii=False)
        except (TypeError, ValueError) as e:
            return f"value not serializable: {e}"
        if len(encoded) > MyTool._MAX_VALUE_BYTES:
            return f"value exceeds {MyTool._MAX_VALUE_BYTES} bytes (got {len(encoded)})"
        return None

    def _redact_value(self, key: str, value: Any) -> str:
        """Return a safe repr of ``value`` for audit logs and chat output.

        Redacts the whole value when ``key`` is sensitive or the value is a
        secret-shaped scalar. Recurses into dict/list/tuple values so nested
        secrets under a benign top-level key (e.g. ``data={"api_key": ...}``)
        are also redacted before reaching chat or logs (D8).
        """
        return repr(self._redacted_copy(key, value))

    @classmethod
    def _redacted_copy(cls, key: str, value: Any) -> Any:
        if cls._is_sensitive_field_name(key):
            return "<redacted>"
        if isinstance(value, str):
            return "<redacted>" if _SECRET_VALUE_RE.match(value) else value
        if isinstance(value, dict):
            return {str(k): cls._redacted_copy(str(k), v) for k, v in value.items()}
        if isinstance(value, list):
            return [cls._redacted_copy("", v) for v in value]
        if isinstance(value, tuple):
            return tuple(cls._redacted_copy("", v) for v in value)
        return value

    # ------------------------------------------------------------------
    # Path resolution
    # ------------------------------------------------------------------

    def _resolve_path(self, path: str) -> tuple[Any, str | None]:
        parts = path.split(".")
        obj = self._runtime_state
        for part in parts:
            if part in self._DENIED_ATTRS or part.startswith("__"):
                return None, f"'{part}' is not accessible"
            if part in self.BLOCKED:
                return None, f"'{part}' is not accessible"
            if part.lower() in self._SENSITIVE_NAMES:
                return None, f"'{part}' is not accessible"
            try:
                if isinstance(obj, dict):
                    if part in obj:
                        obj = obj[part]
                    else:
                        return None, f"'{part}' not found in dict"
                else:
                    obj = getattr(obj, part)
            except (KeyError, AttributeError) as e:
                return None, f"'{part}' not found: {e}"
        return obj, None

    @staticmethod
    def _validate_key(key: str | None, label: str = "key") -> str | None:
        if not key or not key.strip():
            return f"Error: '{label}' cannot be empty or whitespace"
        return None

    # ------------------------------------------------------------------
    # Smart formatting
    # ------------------------------------------------------------------

    @staticmethod
    def _format_status(st: "SubagentStatus", indent: str = "  ") -> str:
        elapsed = time.monotonic() - st.started_at
        tool_summary = ", ".join(
            f"{e.get('name', '?')}({e.get('status', '?')})" for e in st.tool_events[-5:]
        ) or "none"
        lines = [
            f"{indent}phase: {st.phase}, iteration: {st.iteration}, elapsed: {elapsed:.1f}s",
            f"{indent}tools: {tool_summary}",
            f"{indent}usage: {st.usage or 'n/a'}",
        ]
        if st.error:
            lines.append(f"{indent}error: {st.error}")
        if st.stop_reason:
            lines.append(f"{indent}stop_reason: {st.stop_reason}")
        return "\n".join(lines)

    @staticmethod
    def _format_value(val: Any, key: str = "") -> str:
        if _is_subagent_status(val):
            header = f"Subagent [{val.task_id}] '{val.label}'"
            detail = MyTool._format_status(val, "  ")
            return f"{header}\n  task: {val.task_description}\n{detail}"
        # SubagentManager: delegate to its _task_statuses dict
        if hasattr(val, "_task_statuses") and isinstance(val._task_statuses, dict):
            return MyTool._format_value(val._task_statuses, key)
        if isinstance(val, dict) and val and _is_subagent_status(next(iter(val.values()))):
            prefix = f"{key}: " if key else ""
            lines = [f"{prefix}{len(val)} subagent(s):"]
            for tid, st in val.items():
                detail = MyTool._format_status(st, "    ")
                lines.append(f"  [{tid}] '{st.label}'\n{detail}")
            return "\n".join(lines)
        if hasattr(val, "tool_names"):
            return f"tools: {len(val.tool_names)} registered — {val.tool_names}"
        # Scalar types — repr, with redaction for sensitive keys / secret values
        if isinstance(val, (str, int, float, bool, type(None))):
            if key and MyTool._is_sensitive_field_name(key):
                r = "<redacted>"
            elif isinstance(val, str) and _SECRET_VALUE_RE.match(val):
                r = "<redacted>"
            else:
                r = repr(val)
            return f"{key}: {r}" if key else r
        # Dict — small: show content (recursively redacted), large: show keys for dot-path navigation
        if isinstance(val, dict):
            ks = list(val.keys())
            if not ks:
                return f"{key}: {{}}" if key else "{}"
            if len(ks) <= 5:
                # Recurse via _redacted_copy so nested secrets under a benign
                # top-level key (e.g. {"api_key": "sk-..."}) are also redacted
                # before reaching chat output (D8). The >5-key branch below only
                # surfaces key names, which is safe.
                r = repr(MyTool._redacted_copy(key, val))
                if len(r) <= 200:
                    return f"{key}: {r}" if key else r
            preview = ", ".join(str(k) for k in ks[:15])
            suffix = ", ..." if len(ks) > 15 else ""
            return f"{key}: {{{preview}{suffix}}}" if key else f"{{{preview}{suffix}}}"
        # List/tuple — count for large, recursively redacted repr for small
        if isinstance(val, (list, tuple)):
            if len(val) > 20:
                return f"{key}: [{len(val)} items]" if key else f"[{len(val)} items]"
            r = repr(MyTool._redacted_copy(key, val))
            return f"{key}: {r}" if key else r
        # Complex object — small Pydantic models: show values; others: show field names for navigation
        cls_name = type(val).__name__
        model_fields = getattr(type(val), "model_fields", None)
        if model_fields:
            fields = list(model_fields.keys())
            if len(fields) <= 8:
                # Small config objects: show field=value pairs
                pairs = []
                for f in fields:
                    fv = getattr(val, f, "?")
                    if MyTool._is_sensitive_field_name(f):
                        continue
                    if isinstance(fv, (str, int, float, bool, type(None))):
                        pairs.append(f"{f}={fv!r}")
                    else:
                        pairs.append(f"{f}=<{type(fv).__name__}>")
                preview = ", ".join(pairs)
                return f"{key}: {preview}" if key else preview
        else:
            fields = [a for a in getattr(val, "__dict__", {}) if not a.startswith("__")]
        if fields:
            preview = ", ".join(str(f) for f in fields[:20])
            suffix = ", ..." if len(fields) > 20 else ""
            return f"{key}: <{cls_name}> [{preview}{suffix}]" if key else f"<{cls_name}> [{preview}{suffix}]"
        r = repr(val)
        return f"{key}: {r}" if key else r

    # ------------------------------------------------------------------
    # Action dispatch
    # ------------------------------------------------------------------

    async def execute(
        self,
        action: str,
        key: str | None = None,
        value: Any = None,
        **_kwargs: Any,
    ) -> str:
        if action in ("inspect", "check"):
            return self._inspect(key)
        if not self._modify_allowed:
            if self._allow_scratchpad and action in ("modify", "set"):
                return await self._modify_scratchpad_only(key, value)
            return "Error: set is disabled (tools.my.allow_set is false)"
        if action in ("modify", "set"):
            return await self._modify(key, value)
        return f"Unknown action: {action}"

    # -- inspect --

    def _inspect(self, key: str | None) -> str:
        if not key:
            return self._inspect_all()
        top = key.split(".")[0]
        if top in self._DENIED_ATTRS or top.startswith("__"):
            return f"Error: '{top}' is not accessible"
        # "scratchpad" alias for the caller's session-scoped dict — handled
        # before path resolution so mock/real runtime states behave identically.
        if key == "scratchpad":
            scoped = self._read_scope()
            if scoped is None:
                return "Error: no session context available"
            return self._format_value(scoped, "scratchpad") if scoped else "scratchpad is empty"
        obj, err = self._resolve_path(key)
        if err:
            # Fallback: check session-scoped _runtime_vars for simple keys
            if "." not in key:
                scoped = self._read_scope()
                if scoped is None:
                    return "Error: no session context available"
                if key in scoped:
                    return self._format_value(scoped[key], key)
            return f"Error: {err}"
        # Guard against mock auto-generated attributes
        if "." not in key and not _has_real_attr(self._runtime_state, key):
            scoped = self._read_scope()
            if scoped is not None and key in scoped:
                return self._format_value(scoped[key], key)
            return f"Error: '{key}' not found"
        return self._format_value(obj, key)

    def _inspect_all(self) -> str:
        state = self._runtime_state
        parts: list[str] = []
        # RESTRICTED keys
        for k in self.RESTRICTED:
            parts.append(self._format_value(getattr(state, k, None), k))
        parts.append(self._format_value(state.model_preset, "model_preset"))
        # Other useful top-level keys shown in description
        for k in ("workspace", "provider_retry_mode", "max_tool_result_chars", "_current_iteration", "web_config", "exec_config", "workspace_sandbox", "subagents"):
            if _has_real_attr(state, k):
                parts.append(self._format_value(getattr(state, k, None), k))
        # Token usage
        usage = state._last_usage
        if usage:
            parts.append(self._format_value(usage, "_last_usage"))
        scoped = self._read_scope()
        if scoped is not None and scoped:
            parts.append(self._format_value(scoped, "scratchpad"))
        return "\n".join(parts)

    # -- modify --

    async def _modify_scratchpad_only(self, key: str | None, value: Any) -> str:
        """Scratchpad-only path: allows writing to _runtime_vars but blocks
        all real attribute modifications, dot-paths, restricted keys, and
        sensitive names."""
        if err := self._validate_key(key):
            return err
        # Block dot-paths first — scratchpad keys are simple keys only
        if "." in key:
            self._audit("modify", f"BLOCKED dot-path '{key}' (scratchpad-only mode)")
            return "Error: dot-paths are not allowed in scratchpad-only mode"
        # Block everything that _modify would block
        if key in self.BLOCKED or key in self._DENIED_ATTRS or key.startswith("__") or key.lower() in self._SENSITIVE_NAMES:
            self._audit("modify", f"BLOCKED {key}")
            return f"Error: '{key}' is protected and cannot be modified"
        if key in self.READ_ONLY:
            self._audit("modify", f"READ_ONLY {key}")
            return f"Error: '{key}' is read-only and cannot be modified"
        # Block restricted keys (max_iterations, context_window_tokens, model)
        if key in self.RESTRICTED:
            self._audit("modify", f"BLOCKED restricted '{key}' (scratchpad-only mode)")
            return f"Error: '{key}' cannot be modified in scratchpad-only mode"
        # Block model_preset
        if key == "model_preset":
            self._audit("modify", "BLOCKED model_preset (scratchpad-only mode)")
            return "Error: 'model_preset' cannot be modified in scratchpad-only mode"
        # Block keys that are real attributes on the runtime state
        if _has_real_attr(self._runtime_state, key):
            self._audit("modify", f"BLOCKED real attr '{key}' (scratchpad-only mode)")
            return f"Error: '{key}' is a runtime attribute and cannot be modified in scratchpad-only mode"
        # Only allow JSON-safe values
        if callable(value):
            self._audit("modify", f"REJECTED callable {key}")
            return "Error: cannot store callable values"
        err = self._validate_json_safe(value)
        if err:
            self._audit("modify", f"REJECTED {key}: {err}")
            return f"Error: {err}"
        err = self._check_value_size(value)
        if err:
            self._audit("modify", f"REJECTED {key}: {err}")
            return f"Error: {err}"
        async with self._runtime_state._runtime_vars_lock:
            scoped = self._write_scope()
            if scoped is None:
                return "Error: no session context available"
            if key not in scoped and len(scoped) >= self._MAX_RUNTIME_KEYS:
                self._audit("modify", f"REJECTED {key}: max keys ({self._MAX_RUNTIME_KEYS}) reached")
                return f"Error: scratchpad is full (max {self._MAX_RUNTIME_KEYS} keys). Remove unused keys first."
            old = scoped.get(key)
            scoped[key] = value
            r_old = self._redact_value(key, old)
            r_new = self._redact_value(key, value)
            self._audit("modify", f"scratchpad.{key}: {r_old} -> {r_new}")
            return f"Set scratchpad.{key} = {r_new}"

    async def _modify(self, key: str | None, value: Any) -> str:
        if err := self._validate_key(key):
            return err
        top = key.split(".")[0]
        if top in self.BLOCKED or top in self._DENIED_ATTRS or top.startswith("__") or top.lower() in self._SENSITIVE_NAMES:
            self._audit("modify", f"BLOCKED {key}")
            return f"Error: '{key}' is protected and cannot be modified"
        if top in self.READ_ONLY:
            self._audit("modify", f"READ_ONLY {key}")
            return f"Error: '{key}' is read-only and cannot be modified"
        if "." in key:
            parent_path, leaf = key.rsplit(".", 1)
            if leaf in self._DENIED_ATTRS or leaf.startswith("__"):
                self._audit("modify", f"BLOCKED leaf '{leaf}'")
                return f"Error: '{leaf}' is not accessible"
            if leaf.lower() in self._SENSITIVE_NAMES:
                self._audit("modify", f"BLOCKED sensitive leaf '{leaf}'")
                return f"Error: '{leaf}' is not accessible"
            parent, err = self._resolve_path(parent_path)
            if err:
                return f"Error: {err}"
            if isinstance(parent, dict):
                parent[leaf] = value
            else:
                setattr(parent, leaf, value)
            r_new = self._redact_value(leaf, value)
            self._audit("modify", f"{key} = {r_new}")
            return f"Set {key} = {r_new}"
        if key == "model_preset":
            return await self._modify_model_preset(value)
        if key in self.RESTRICTED:
            return self._modify_restricted(key, value)
        return await self._modify_free(key, value)

    async def _modify_model_preset(self, value: Any) -> str:
        if not isinstance(value, str) or not value.strip():
            return "Error: 'model_preset' must be a non-empty string"
        name = value.strip()
        result = await self._modify_free("model_preset", name)
        if result.startswith("Error:"):
            return result if result.endswith((".", "!", "?")) else f"{result}."
        return (
            f"{result}; model is now {self._runtime_state.model!r}; "
            f"context_window_tokens is now {self._runtime_state.context_window_tokens!r}"
        )

    def _modify_restricted(self, key: str, value: Any) -> str:
        spec = self.RESTRICTED[key]
        expected = spec["type"]
        if expected is int and isinstance(value, bool):
            return f"Error: '{key}' must be {expected.__name__}, got bool"
        if not isinstance(value, expected):
            try:
                value = expected(value)
            except (ValueError, TypeError):
                return f"Error: '{key}' must be {expected.__name__}, got {type(value).__name__}"
        old = getattr(self._runtime_state, key)
        if "min" in spec and value < spec["min"]:
            return f"Error: '{key}' must be >= {spec['min']}"
        if "max" in spec and value > spec["max"]:
            return f"Error: '{key}' must be <= {spec['max']}"
        if "min_len" in spec and len(str(value)) < spec["min_len"]:
            return f"Error: '{key}' must be at least {spec['min_len']} characters"
        setattr(self._runtime_state, key, value)
        if key == "model":
            self._runtime_state._active_preset = None
        sync_replay = getattr(self._runtime_state, "_sync_replay_max_messages", None)
        if key == "context_window_tokens" and callable(sync_replay):
            sync_replay()
        if key == "max_iterations" and hasattr(self._runtime_state, "_sync_subagent_runtime_limits"):
            self._runtime_state._sync_subagent_runtime_limits()
        r_old = self._redact_value(key, old)
        r_new = self._redact_value(key, value)
        self._audit("modify", f"{key}: {r_old} -> {r_new}")
        return f"Set {key} = {r_new} (was {r_old})"

    async def _modify_free(self, key: str, value: Any) -> str:
        if _has_real_attr(self._runtime_state, key):
            old = getattr(self._runtime_state, key)
            if isinstance(old, (str, int, float, bool)):
                old_t, new_t = type(old), type(value)
                if old_t is float and new_t is int:
                    pass  # int → float coercion allowed
                elif old_t is not new_t:
                    self._audit(
                        "modify",
                        f"REJECTED type mismatch {key}: expects {old_t.__name__}, got {new_t.__name__}",
                    )
                    return f"Error: '{key}' expects {old_t.__name__}, got {new_t.__name__}"
            try:
                setattr(self._runtime_state, key, value)
            except (ValueError, KeyError) as e:
                message = str(e.args[0] if isinstance(e, KeyError) and e.args else e).strip('"')
                self._audit("modify", f"REJECTED {key}: {message}")
                return f"Error: {message}"
            r_old = self._redact_value(key, old)
            r_new = self._redact_value(key, value)
            self._audit("modify", f"{key}: {r_old} -> {r_new}")
            return f"Set {key} = {r_new} (was {r_old})"
        if callable(value):
            self._audit("modify", f"REJECTED callable {key}")
            return "Error: cannot store callable values"
        err = self._validate_json_safe(value)
        if err:
            self._audit("modify", f"REJECTED {key}: {err}")
            return f"Error: {err}"
        err = self._check_value_size(value)
        if err:
            self._audit("modify", f"REJECTED {key}: {err}")
            return f"Error: {err}"
        async with self._runtime_state._runtime_vars_lock:
            scoped = self._write_scope()
            if scoped is None:
                return "Error: no session context available"
            if key not in scoped and len(scoped) >= self._MAX_RUNTIME_KEYS:
                self._audit("modify", f"REJECTED {key}: max keys ({self._MAX_RUNTIME_KEYS}) reached")
                return f"Error: scratchpad is full (max {self._MAX_RUNTIME_KEYS} keys). Remove unused keys first."
            old = scoped.get(key)
            scoped[key] = value
            r_old = self._redact_value(key, old)
            r_new = self._redact_value(key, value)
            self._audit("modify", f"scratchpad.{key}: {r_old} -> {r_new}")
            return f"Set scratchpad.{key} = {r_new}"

    @classmethod
    def _validate_json_safe(cls, value: Any, depth: int = 0) -> str | None:
        if depth > 10:
            return "value nesting too deep (max 10 levels)"
        if isinstance(value, (str, int, float, bool, type(None))):
            return None
        if isinstance(value, list):
            for i, item in enumerate(value):
                if err := cls._validate_json_safe(item, depth + 1):
                    return f"list[{i}] contains {err}"
            return None
        if isinstance(value, dict):
            for k, v in value.items():
                if not isinstance(k, str):
                    return f"dict key must be str, got {type(k).__name__}"
                if err := cls._validate_json_safe(v, depth + 1):
                    return f"dict key '{k}' contains {err}"
            return None
        return f"unsupported type {type(value).__name__}"
